import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, join } from "node:path";
import { parse as parseYaml } from "yaml";
import { compile } from "./compile.js";
import { loadToken } from "./load.js";
import { runnerFromSpec } from "./eval/runners/index.js";
import { imageRunnerFromSpec } from "./eval/runners/image-index.js";
import { compileImagePrompt, briefAsProse } from "./compile.js";
import { lintSource, formatReport } from "./lint/engine.js";

function headerComment(kind: "html" | "svg", tokenId: string, modelId: string): string {
  const ts = new Date().toISOString();
  const open = "<!--";
  const close = "-->";
  return `${open}\n  Generated by: ahd try\n  Token:  ${tokenId}\n  Model:  ${modelId}\n  When:   ${ts}\n  Lint:   ahd lint <path>\n  Note:   Demo artifact, not production output.\n${close}\n`;
}

function pickDefaultTextModel(): string {
  if (process.env.CF_API_TOKEN && process.env.CF_ACCOUNT_ID) {
    return "cf:@cf/mistralai/mistral-small-3.1-24b-instruct";
  }
  return "mock-swiss";
}

function pickDefaultImageModel(): string | null {
  if (process.env.CF_API_TOKEN && process.env.CF_ACCOUNT_ID) {
    return "cfimg:@cf/black-forest-labs/flux-1-schnell";
  }
  return null;
}

function timestampSlug(): string {
  return new Date().toISOString().replace(/[:.]/g, "-").replace(/Z$/, "");
}

export async function runTry(options: {
  tokensDir: string;
  briefPath: string;
  tokenOverride?: string;
  modelSpec?: string;
  outDir?: string;
  skipLint?: boolean;
}): Promise<{ outPath: string; violations: number }> {
  const brief = parseYaml(await readFile(options.briefPath, "utf8"));
  const tokenId = options.tokenOverride ?? brief.token;
  if (!tokenId) {
    throw new Error("Brief has no `token:` field and no --token override was given");
  }
  const token = await loadToken(options.tokensDir, tokenId);
  const compiled = compile(brief, token, "final");
  const modelSpec = options.modelSpec ?? pickDefaultTextModel();
  const runner = await runnerFromSpec(modelSpec);

  const outDir = options.outDir ?? "out";
  await mkdir(outDir, { recursive: true });

  const userPrompt = [
    "Follow the brief and style direction above exactly.",
    "",
    briefAsProse(brief),
    "",
    "Return a single, self-contained, valid HTML5 document only — no prose, no fenced code, no multiple directions. Start with <!doctype html> and end with </html>.",
  ].join("\n");

  const out = await runner.run({
    systemPrompt: compiled.prompts.generic,
    userPrompt,
    maxTokens: 12000,
    seed: 1,
  });

  const header = headerComment("html", tokenId, runner.id);
  const stamped = out.html.startsWith("<!doctype")
    ? out.html.replace(/^<!doctype[^>]*>\s*/i, (m) => m + header)
    : header + out.html;

  const outPath = join(outDir, `ahd-try-${tokenId}-${timestampSlug()}.html`);
  await writeFile(outPath, stamped);

  let violations = 0;
  if (!options.skipLint) {
    const report = lintSource({ file: outPath, html: stamped, css: "" });
    violations = report.violations.length;
    console.log(`\nwrote ${outPath}`);
    console.log(`model: ${runner.id}`);
    console.log(`token: ${tokenId}`);
    console.log("");
    console.log(formatReport(report));
  } else {
    console.log(`wrote ${outPath}`);
  }

  return { outPath, violations };
}

export async function runTryImage(options: {
  tokensDir: string;
  briefPath: string;
  tokenOverride?: string;
  modelSpec?: string;
  outDir?: string;
}): Promise<{ outPath: string }> {
  const brief = parseYaml(await readFile(options.briefPath, "utf8"));
  const tokenId = options.tokenOverride ?? brief.token;
  if (!tokenId) {
    throw new Error("Brief has no `token:` field and no --token override was given");
  }
  const token = await loadToken(options.tokensDir, tokenId);
  const { prompt, negativePrompt } = compileImagePrompt(brief, token);
  const modelSpec = options.modelSpec ?? pickDefaultImageModel();
  if (!modelSpec) {
    throw new Error(
      "ahd try-image requires a CF_API_TOKEN + CF_ACCOUNT_ID or an explicit --model spec. There is no offline image mock.",
    );
  }
  const runner = imageRunnerFromSpec(modelSpec);

  const outDir = options.outDir ?? "out";
  await mkdir(outDir, { recursive: true });

  const result = await runner.run({
    prompt,
    negativePrompt,
    seed: 1,
    width: 1024,
    height: 1024,
  });

  const slug = timestampSlug();
  const outPath = join(outDir, `ahd-try-${tokenId}-${slug}.png`);
  await writeFile(outPath, Buffer.from(result.pngBase64, "base64"));

  const metaPath = join(outDir, `ahd-try-${tokenId}-${slug}.meta.txt`);
  await writeFile(
    metaPath,
    [
      `Generated by: ahd try-image`,
      `Token:  ${tokenId}`,
      `Model:  ${runner.id}`,
      `When:   ${new Date().toISOString()}`,
      `Critique:   ahd critique ${tokenId} --samples <dir-above>`,
      `Note:   Demo artifact, not production output.`,
      ``,
      `--- prompt ---`,
      prompt,
      ``,
      `--- negative ---`,
      negativePrompt,
    ].join("\n"),
  );

  console.log(`wrote ${outPath}`);
  console.log(`wrote ${metaPath}`);
  console.log(`model: ${runner.id}`);
  console.log(`token: ${tokenId}`);

  return { outPath };
}
